name: CI

on:
  push:
    branches: [main, develop]
    tags: ['v*']
  pull_request:
    branches: [main]

env:
  GITEA_URL: https://git.uuxo.net

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: golang:1.24-bookworm
    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y git ca-certificates python3

      - name: Checkout code
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git clone --depth 1 --branch ${GITHUB_REF_NAME} ${{ env.GITEA_URL }}/${GITHUB_REPOSITORY}.git .

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Run go vet
        run: go vet ./...

      - name: Check formatting
        run: |
          if [ -n "$(gofmt -s -l .)" ]; then
            echo "Code is not formatted. Run 'go fmt ./...'"
            gofmt -s -l .
            exit 1
          fi

      - name: Validate config templates
        run: |
          echo "Validating TOML config templates..."
          for file in templates/*.toml examples/*.toml; do
            if [ -f "$file" ]; then
              echo "Checking $file"
              python3 -c "
          import tomllib, sys
          try:
              with open('$file', 'rb') as f:
                  tomllib.load(f)
              print('  OK')
          except Exception as e:
              print(f'  FAIL: {e}', file=sys.stderr)
              sys.exit(1)
          "
            fi
          done

  build:
    name: Build (${{ matrix.goos }}-${{ matrix.goarch }})
    runs-on: ubuntu-latest
    needs: test
    container:
      image: golang:1.24-bookworm
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: arm
            goarm: "7"
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: amd64
    steps:
      - name: Install git
        run: apt-get update && apt-get install -y git ca-certificates

      - name: Checkout code
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git clone --depth 1 --branch ${GITHUB_REF_NAME} ${{ env.GITEA_URL }}/${GITHUB_REPOSITORY}.git .

      - name: Build binaries
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
          CGO_ENABLED: "0"
        run: |
          SUFFIX=""
          if [ "${{ matrix.goos }}" = "windows" ]; then
            SUFFIX=".exe"
          fi
          ARCH="${{ matrix.goarch }}"
          if [ -n "${{ matrix.goarm }}" ]; then
            ARCH="${{ matrix.goarch }}v${{ matrix.goarm }}"
          fi

          mkdir -p bin

          echo "Building hmac-file-server..."
          go build -v -ldflags="-s -w" \
            -o "bin/hmac-file-server-${{ matrix.goos }}-${ARCH}${SUFFIX}" \
            ./cmd/server/

          echo "Building hmac-monitor..."
          go build -v -ldflags="-s -w" \
            -o "bin/hmac-monitor-${{ matrix.goos }}-${ARCH}${SUFFIX}" \
            ./cmd/monitor/

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [test, build]
    if: startsWith(github.ref, 'refs/tags/v')
    container:
      image: golang:1.24-bookworm
    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y git ca-certificates curl python3

      - name: Checkout code
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git clone --depth 1 --branch ${GITHUB_REF_NAME} ${{ env.GITEA_URL }}/${GITHUB_REPOSITORY}.git .

      - name: Build all release binaries
        run: |
          mkdir -p release
          for target in linux/amd64 linux/arm64 linux/arm/7 darwin/amd64 darwin/arm64 windows/amd64; do
            IFS='/' read -r goos goarch goarm <<< "$target"
            suffix=""
            arch="$goarch"
            [ "$goos" = "windows" ] && suffix=".exe"
            [ -n "$goarm" ] && arch="${goarch}v${goarm}"

            export GOOS="$goos" GOARCH="$goarch" GOARM="$goarm" CGO_ENABLED=0
            echo "Building ${goos}-${arch}..."
            go build -ldflags="-s -w" -o "release/hmac-file-server-${goos}-${arch}${suffix}" ./cmd/server/
            go build -ldflags="-s -w" -o "release/hmac-monitor-${goos}-${arch}${suffix}" ./cmd/monitor/
          done
          cd release && sha256sum * > SHA256SUMS
          echo "Release assets:" && ls -lh

      - name: Create Gitea release and upload assets
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          API_URL="${{ env.GITEA_URL }}/api/v1/repos/${GITHUB_REPOSITORY}/releases"

          RELEASE_RESPONSE=$(curl -s -X POST "$API_URL" \
            -H "Authorization: token ${GITEA_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "{
              \"tag_name\": \"${TAG}\",
              \"name\": \"${TAG}\",
              \"body\": \"Release ${TAG}\n\nBuilt from commit ${GITHUB_SHA::8}.\",
              \"draft\": false,
              \"prerelease\": false
            }")

          RELEASE_ID=$(echo "$RELEASE_RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
          echo "Created release ID: $RELEASE_ID"

          UPLOAD_URL="${{ env.GITEA_URL }}/api/v1/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets"
          for file in release/*; do
            FILENAME=$(basename "$file")
            echo "Uploading $FILENAME..."
            curl -s -X POST "${UPLOAD_URL}?name=${FILENAME}" \
              -H "Authorization: token ${GITEA_TOKEN}" \
              -H "Content-Type: application/octet-stream" \
              --data-binary "@${file}"
          done
          echo "All assets uploaded."


