name: CI

on:
  push:
    branches: [main, develop]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Run go vet
        run: go vet ./...

      - name: Check formatting
        run: |
          if [ -n "$(gofmt -s -l .)" ]; then
            echo "Code is not formatted. Run 'go fmt ./...'"
            gofmt -s -l .
            exit 1
          fi

      - name: Validate config templates
        run: |
          echo "Validating TOML config templates..."
          go run -mod=mod golang.org/x/tools/cmd/goimports@latest -l . > /dev/null 2>&1 || true
          for file in templates/*.toml examples/*.toml; do
            if [ -f "$file" ]; then
              echo "Checking $file"
              python3 -c "
          import tomllib, sys
          try:
              with open('$file', 'rb') as f:
                  tomllib.load(f)
              print('  OK')
          except Exception as e:
              print(f'  FAIL: {e}', file=sys.stderr)
              sys.exit(1)
          "
            fi
          done

  build:
    name: Build (${{ matrix.goos }}-${{ matrix.goarch }})
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: arm
            goarm: "7"
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build binaries
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
          CGO_ENABLED: "0"
        run: |
          SUFFIX=""
          if [ "${{ matrix.goos }}" = "windows" ]; then
            SUFFIX=".exe"
          fi
          ARCH="${{ matrix.goarch }}"
          if [ -n "${{ matrix.goarm }}" ]; then
            ARCH="${{ matrix.goarch }}v${{ matrix.goarm }}"
          fi

          mkdir -p bin

          echo "Building hmac-file-server..."
          go build -v -ldflags="-s -w" \
            -o "bin/hmac-file-server-${{ matrix.goos }}-${ARCH}${SUFFIX}" \
            ./cmd/server/

          echo "Building hmac-monitor..."
          go build -v -ldflags="-s -w" \
            -o "bin/hmac-monitor-${{ matrix.goos }}-${ARCH}${SUFFIX}" \
            ./cmd/monitor/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: bin/*

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Gitea Registry
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | docker login git.uuxo.net -u "${{ secrets.REGISTRY_USER }}" --password-stdin

      - name: Determine tags
        id: tags
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "tags=git.uuxo.net/uuxo/hmac-file-server:${VERSION},git.uuxo.net/uuxo/hmac-file-server:latest" >> "$GITHUB_OUTPUT"
          else
            echo "tags=git.uuxo.net/uuxo/hmac-file-server:${GITHUB_SHA::8},git.uuxo.net/uuxo/hmac-file-server:main" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push multi-arch image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file Dockerfile.multiarch \
            --push \
            $(echo "${{ steps.tags.outputs.tags }}" | sed 's/,/ -t /g; s/^/-t /') \
            .

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [test, build]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release
          find artifacts -name 'hmac-file-server-*' -o -name 'hmac-monitor-*' | while read f; do
            cp "$f" release/
          done
          cd release
          sha256sum * > SHA256SUMS
          echo "Release assets:"
          ls -lh

      - name: Create Gitea release
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          API_URL="https://git.uuxo.net/api/v1/repos/${GITHUB_REPOSITORY}/releases"

          # Create release
          RELEASE_RESPONSE=$(curl -s -X POST "$API_URL" \
            -H "Authorization: token ${GITEA_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "{
              \"tag_name\": \"${TAG}\",
              \"name\": \"${TAG}\",
              \"body\": \"Release ${TAG}\n\nBuilt from commit ${GITHUB_SHA::8}.\",
              \"draft\": false,
              \"prerelease\": false
            }")

          RELEASE_ID=$(echo "$RELEASE_RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
          echo "Created release ID: $RELEASE_ID"

          # Upload each asset
          UPLOAD_URL="https://git.uuxo.net/api/v1/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets"
          for file in release/*; do
            FILENAME=$(basename "$file")
            echo "Uploading $FILENAME..."
            curl -s -X POST "${UPLOAD_URL}?name=${FILENAME}" \
              -H "Authorization: token ${GITEA_TOKEN}" \
              -H "Content-Type: application/octet-stream" \
              --data-binary "@${file}"
          done
          echo "All assets uploaded."


