#[server]
ListenPort = ":8080"  # Port for the file server to listen on
UnixSocket = false  # Use Unix sockets if true, otherwise TCP
Secret = "supa-secret-maria-und-josef"  # HMAC secret for securing uploads
StoreDir = "/home/renz/source/hmac-file-server/cmd/server/hmacdata"
UploadSubDir = "upload"  # Subdirectory for uploads
LogLevel = "info"  # Logging level: "debug", "info", "warn", "error"
LogFile = "/home/renz/source/hmac-file-server/cmd/server/hmacdata/hmac-file-server.log"  # Log file path
MetricsEnabled = true  # Enable Prometheus metrics
MetricsPort = ":9090"  # Port for Prometheus metrics server

# Fallback database configuration (optional)
FallbackEnabled = false  # Enable fallback to a database if Redis is unavailable
FallbackDBType = "postgres"  # Fallback database type ("postgres" or "mysql")
FallbackDBHost = "localhost"  # Fallback database host
FallbackDBUser = "your_db_user"  # Fallback database username
FallbackDBPassword = "your_db_password"  # Fallback database password
FallbackDBName = "your_db_name"  # Fallback database name

# Graceful shutdown
GracefulShutdownTimeout = 30  # Timeout for graceful shutdowns (in seconds)

# FileTTL
FileTTL = "120d"
ResumableUploadsEnabled = true 
MaxVersions = 2
EnableVersioning = false

ChunkedUploadsEnabled = true
ChunkSize = 16384   # 64kb for small mobile networks

# Throttle Relaxement
ThrottleEnabled = false
ThrottleEffect = 30   # Throttle effect in seconds

# Garbage Collector and Goroutines
DynamicCpus = false
DynCores = 1
GCEnabled = true
GCInterval = "30m"

# RedisDB
RedisEnabled = true
RedisAddr = "localhost:6379"
RedisPassword = ""
