# Server Settings
ListenIP = "127.0.0.1"
ListenPort = ":8080"

MetricsEnabled = true
ListenIPMetrics = "127.0.0.1"  # IP address for the metrics server
MetricsPort = "9090"  

UnixSocket = false
Secret = "freaky-karl-nicht-noetig-gewesen"
StoreDir = ""./TestUpload""
UploadSubDir = "upload"
LoggingEnabled = true
LogLevel = "info"
LogFile = "/var/log/hmac-file-server.log"

# Workers and connections
NumWorkers = 2
UploadQueueSize = 50

# IP Management Settings
EnableIPManagement = false
IPSource = "header"
NginxLogFile = "/var/log/nginx/stream-access.log"

# Graceful shutdown
GracefulShutdownTimeout = 60

# File TTL
FileTTL = "365d"
ResumableUploadsEnabled = true
ResumableDownloadsEnabled = true
MaxVersions = 1
EnableVersioning = false

# Upload/Download settings
ChunkedUploadsEnabled = true
ChunkSize = 8192

# Redis settings
RedisEnabled = true
RedisAddr = "localhost:6379"
RedisPassword = ""
RedisDBIndex = 0
RedisHealthCheckInterval = "120s"

# Server timeout settings
ReadTimeout = "4800s"
WriteTimeout = "4800s"
IdleTimeout = "4800s"
SessionRefreshInterval = "24h"

# ClamAV Configuration
ClamAVEnabled = true
NumScanWorkers = 2
ClamAVSocket = "/var/run/clamav/clamd.ctl"
#ClamAVSocket = "tcp:127.0.0.1:3310"

# Security settings
RateLimitingEnabled = false
MaxRequestsPerMinute = 60
RateLimitInterval = "1m"
BlockedUserAgents = ["MisskeyBot/1.0", "EvilCrawler"]

# Fail2Ban
Enable = false
Jail = "hmac-auth"
BlockCommand = "/usr/bin/fail2ban-client set hmac-auth ban <IP>"
UnblockCommand = "/usr/bin/fail2ban-client set hmac-auth unban <IP>"
MaxRetries = 3
BanTime = "3600s"

# Allowed file extensions including image, video, and document formats
AllowedExtensions = [
    # Document formats
    ".txt", ".pdf",

    # Image formats
    ".png",".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".svg", ".webp",

    # Video formats
    ".wav", ".mp4", ".avi", ".mkv", ".mov", ".wmv", ".flv", ".webm", ".mpeg", ".mpg", ".m4v", ".3gp", ".3g2",

    # Audio formats
    ".mp3", ".ogg"
]
