# Server settings
ListenPort = ":8080"                           # Port for the file server to listen on
UnixSocket = false                              # Use Unix sockets if true, otherwise TCP
Secret = "supa-secret-maria-und-josef"        # HMAC secret for securing uploads
StoreDir = "./hmacdata"                        # Directory for storing uploaded files
UploadSubDir = "upload"                        # Subdirectory for uploads
LogLevel = "info"                              # Logging level: "debug", "info", "warn", "error"
LogFile = "./hmacdata/hmac-file-server.log"    # Log file path
MetricsEnabled = true                           # Enable Prometheus metrics
MetricsPort = ":9090"                          # Port for Prometheus metrics server

# Workers and connections
NumWorkers = 25                                 # Set number of workers
UploadQueueSize = 10000                         # Set upload queue size for handling multiple uploads

# Fallback database configuration (optional)
FallbackEnabled = false                         # Enable fallback to a database if Redis is unavailable
FallbackDBType = "postgres"                    # Fallback database type ("postgres" or "mysql")
FallbackDBHost = "localhost"                   # Fallback database host
FallbackDBUser = "your_db_user"                # Fallback database username
FallbackDBPassword = "your_db_password"        # Fallback database password
FallbackDBName = "your_db_name"                # Fallback database name

# Graceful shutdown
GracefulShutdownTimeout = 30                    # Timeout for graceful shutdowns (in seconds)

# File TTL
FileTTL = "120d"                               # Optional TTL for file expiration (default: "30d")
ResumableUploadsEnabled = true                  # Enable or disable resumable uploads
ResumableDl = true                             # Enable or disable resumable downloads
MaxVersions = 2                                 # Maximum number of file versions to keep
EnableVersioning = true                         # Enable file versioning
AuditLogFile = "/home/hmac-file-server/audit.log" # Path for audit log

# Upload/Download settings
ChunkedUploadsEnabled = false                    # Enable or disable chunked uploads
ChunkSize = 4096                                # Size of each chunk in bytes (4 KB for small mobile networks)

# Throttle Relaxation
ThrottleEnabled = false                          # Enable throttling
ThrottleEffect = 30                            # Throttle effect in seconds
# MaxConcurrentUploadsPerConnection = 4        # Maximum concurrent uploads per connection

# Garbage Collector and Goroutines
DynamicCpus = false                              # Enable dynamic CPU allocation
DynCores = 1                                    # Number of dynamic cores
GCEnabled = true                                # Enable garbage collection
GCInterval = "30m"                              # Interval for garbage collection

# RedisDB settings
RedisEnabled = false                             # Enable Redis for caching
RedisAddr = "localhost:6379"                   # Redis server address
RedisPassword = ""                              # Redis password (if any)
