#XMPP Settings
# Server Settings
ListenIP = "127.0.0.1"                      # IP address to bind the file server
ListenPort = "8080"                         # Port for the file server
UnixSocket = false                          # Use Unix socket (set to true for socket usage)
Secret = "your-secret-key"                  # Replace with a strong secret for HMAC
StoreDir = "./TestUpload"                   # Directory for storing uploaded files
UploadSubDir = "upload"                     # Subdirectory for uploads
LoggingEnabled = false                       # Enable or disable logging
LogLevel = "info"                           # Logging level: "debug", "info", "warn", "error"
LogFile = "./hmac-file-server.log"          # Log file path

# Metrics Settings
MetricsEnabled = true                       # Enable Prometheus metrics
MetricsPort = "9090"                        # Port for the metrics server
ListenIPMetrics = "127.0.0.1"               # Metrics server IP address

# Worker and Queue Settings
NumWorkers = 5                              # Number of worker threads for uploads
UploadQueueSize = 5000                      # Size of the upload queue

# Graceful Shutdown
GracefulShutdownTimeout = 60                # Timeout in seconds for graceful shutdown

# File Expiration and Versioning
FileTTL = "90d"                             # Time-to-live for files before expiration
EnableVersioning = true                     # Enable file versioning
MaxVersions = 3                             # Maximum number of versions to retain
ResumableUploadsEnabled = true              # Enable resumable uploads
ResumableDownloadsEnabled = true            # Enable resumable downloads

# Upload/Download Chunk Settings
ChunkedUploadsEnabled = true                # Enable chunked uploads
ChunkSize = 65536                           # Chunk size in bytes (64 KB)

# Redis Configuration
RedisEnabled = false                        # Enable Redis integration
RedisAddr = "localhost:6379"                # Address of the Redis server
RedisPassword = ""                          # Redis password
RedisDBIndex = 1                            # Redis database index

# Timeout Settings
ReadTimeout = "1h"                          # Timeout for reading requests
WriteTimeout = "1h"                         # Timeout for writing responses
IdleTimeout = "30m"                         # Timeout for idle connections

# ClamAV Configuration
ClamAVEnabled = false                       # Enable ClamAV for file scanning
ClamAVSocket = "/var/run/clamav/clamd.ctl"  # Path to the ClamAV socket (Unix or TCP)

# Allowed File Extensions
AllowedExtensions = [
    ".txt", ".pdf",                         # Document formats
    ".jpg", ".jpeg", ".png", ".gif",        # Image formats
    ".bmp", ".tiff", ".svg", ".webp",
    ".mp4", ".avi", ".mkv", ".mov",         # Video formats
    ".wmv", ".flv", ".webm", ".mpeg",
    ".mpg", ".m4v", ".3gp", ".3g2",
    ".mp3", ".ogg"                          # Audio formats
]

# IP Management
[IPManagement]
IPSource = "header"                         # IP source (e.g., "header" or "nginx-log")
NginxLogFile = ""                           # Path to NGINX log file (if using "nginx-log")

# Encryption Settings
[Encryption]
Method = "aes"                              # Encryption method: "aes", "hmac", or "xor"
XOREnabled = false                          # Enable XOR encryption (if method is "xor")
AESKey = ""                                 # AES key (will be derived if not provided)

# TLS Settings
[TLS]
EnableTLS = false                           # Enable TLS for secure connections
CertDir = ""                                # Path to TLS certificate directory
Hostnames = []                              # List of hostnames for TLS
UseStaging = false                          # Use Let's Encrypt staging server for testing
