[server]
listenport = "9090"
unixsocket = true
storagepath = "/var/hmac/uploads"
loglevel = "debug"
logfile = "/var/log/hmac-file-server.log"
metricsenabled = false
metricsport = "9091"
filettl = "180d"
minfreebytes = "50GB"
deduplicationenabled = false
autoadjustworkers = false
networkevents = true
temppath = "/tmp/hmac"
loggingjson = true
pidfilepath = "/var/run/hmac_server.pid"
cleanuponexit = false

[iso]
enabled = false
size = "1TB"
mountpoint = "/mnt/nfs_vol01/hmac-file-server/iso/"
charset = "utf-8"

[timeouts]
readtimeout = "1800s"
writetimeout = "1800s"
idletimeout = "1800s"

[security]
secret = "a-orc-and-a-humans-is-drinking-ale"

[versioning]
enableversioning = false
maxversions = 1

[uploads]
resumableuploadsenabled = false
chunkeduploadsenabled = false
chunksize = "64MB"
allowedextensions = [".txt", ".pdf", ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".tiff", ".svg", ".webp", ".wav", ".mp4", ".avi", ".mkv", ".mov", ".wmv", ".flv", ".webm", ".mpeg", ".mpg", ".m4v", ".3gp", ".3g2", ".mp3", ".ogg", ".zip", ".rar"]

[downloads]
resumabledownloadsenabled = true
chunkeddownloadsenabled = true
chunksize = "64MB"

[clamav]
clamavenabled = false
clamavsocket = "/var/run/clamav/clamd.ctl"
numscanworkers = 4
scanfileextensions = [".exe", ".dll", ".bin", ".com", ".bat", ".sh", ".php", ".js"]

[redis]
redisenabled = true
redisdbindex = 1
redisaddr = "redis-server:6379"
redispassword = "securepassword"
redishealthcheckinterval = "60s"

[workers]
numworkers = 4
uploadqueuesize = 1000

[file]
filerevision = 1
