steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Set up Go
    uses: actions/setup-go@v2
    with:
      go-version: '^1.17'

  - name: Build Server
    run: |
      cd cmd/server
      go build -o hmac-file-server main.go

  - name: Start Server
    run: |
      cd cmd/server
      ./hmac-file-server -config ./config.toml &
      echo $! > server.pid
    shell: bash

  - name: Wait for Server to Start
    run: sleep 5

  - name: Run Tests
    run: go test ./... -v

  - name: Stop Server
    run: |
      kill $(cat cmd/server/server.pid)
    shell: bash
